# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: trigger the automated test in another repo
      uses: peter-evans/repository-dispatch@v2 
      with: 
        token: ${{secrets.REPO_ACCESS_TOKEN}}
        repository: rehankhan008/react-project
        event-type: my-event
        client-payload: '{"github":${{ toJson(github) }}}'

  deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |


            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash . ~/.nvm/nvm.sh
            sudo apt-get install -y nodejs
            sudo npm install -g pm2
            pm2 start npm --name "api" -- run start
            git pull origin main
            npm install
            npm run build
            pm2 restart api
            # npm install 18
            # npm install -g pm2
            # pm2 start npm --name "api" -- run start
            # git pull origin main 
            # npm install 
            # npm run build
            # pm2 restart api
            
    
